# CHAPTER 3

Q2.

In [1]:
def my_mult_operation(a, b, operation):
    if operation == "plus":
        return a + b
    elif operation == "minus":
        return a - b
    elif operation == "mult":
        return a * b
    elif operation == "div":
        if b == 0:
            return None  # Handle division by zero
        return a / b
    elif operation == "pow":
        return a ** b
    else:
        return None
    
my_mult_operation(5,2,"plus")

7

Q3.

In [2]:
def my_inside_triangle(x, y):
    if x < 0 or y < 0 or x + y > 1:
        return "outside"
    elif x == 0 or y == 0 or x + y == 1:
        return "border"
    else:
        return "inside"
    
my_inside_triangle(2,0)

'outside'

Q8.

In [3]:
import cmath  # Import for complex math

def my_n_roots(a, b, c):

    delta = (b**2) - 4*(a*c)

    if delta > 0:
        n_roots = 2
        r1 = (-b - delta**0.5) / (2*a)
        r2 = (-b + delta**0.5) / (2*a)
        r = [r1, r2]
    elif delta == 0:
        n_roots = 1
        r = [-b / (2*a)]
    else:  # delta < 0
        n_roots = -2 #-2 represents that it has 2 imaginary roots.
        r1 = (-b - cmath.sqrt(delta)) / (2 * a)
        r2 = (-b + cmath.sqrt(delta)) / (2 * a)
        r = [r1, r2]
    return n_roots, r

my_n_roots(1,1,1)

(-2, [(-0.5-0.8660254037844386j), (-0.5+0.8660254037844386j)])

Q9.

In [4]:
def f(x):
    return x**2

def g(x):
    return 2*x + 1

def my_split_function(f, g, a, b, x):
    if x <= a:
        return f(x)
    elif x >= b:
        return g(x)
    else:
        return 0

my_split_function(f,g,1,2,3)

7

# CHAPTER 5

Q4.

In [5]:
import numpy as np

def my_trig_odd_even(m):
    if not isinstance(m, np.ndarray):
      return None
    q = np.zeros_like(m, dtype=float)  # Initialize q with the same shape and float type
    for i in range(m.shape[0]):
        for j in range(m.shape[1]):
            if m[i, j] % 2 == 0:  # Check if even
                q[i, j] = np.sin(m[i, j])
            else:  # If odd
                q[i, j] = np.cos(m[i, j])
    return q
m = np.array([[1, 2, 3], [4, 5, 6]])
q = my_trig_odd_even(m)
print(m)
print(q)

[[1 2 3]
 [4 5 6]]
[[ 0.54030231  0.90929743 -0.9899925 ]
 [-0.7568025   0.28366219 -0.2794155 ]]


Q5.

In [6]:
def my_mat_mult(P, Q):
    if not isinstance(P, np.ndarray) or not isinstance(Q, np.ndarray):
        return None

    m = P.shape[0]  # Number of rows in P
    p = P.shape[1]  # Number of columns in P
    q_rows = Q.shape[0] #Number of rows in Q
    n = Q.shape[1]  # Number of columns in Q
    
    if p != q_rows:  # Check if matrices can be multiplied
        return None

    M = np.zeros((m, n))  # Initialize the result matrix M with zeros

    for i in range(m):      # Iterate through rows of P (and rows of M)
        for j in range(n):  # Iterate through columns of Q (and columns of M)
            for k in range(p):  # Iterate through columns of P and rows of Q
                M[i, j] += P[i, k] * Q[k, j]

    return M
P = np.array([[1, 2], [3, 4]])
Q = np.array([[1, 0], [0, 1]])
M = my_mat_mult(P, Q)
print("Matrix P:\n",P)
print("Matrix Q:\n",Q)
print("Matrix Product M (P * Q):\n", M)


Matrix P:
 [[1 2]
 [3 4]]
Matrix Q:
 [[1 0]
 [0 1]]
Matrix Product M (P * Q):
 [[1. 2.]
 [3. 4.]]


Q8.

In [7]:
import random

def my_monopoly_dice():
    total = 0
    while True:
        die1 = random.randint(1, 6)
        die2 = random.randint(1, 6)
        total += die1 + die2
        if die1 != die2:
            break
    return total
for _ in range(10):
    print(my_monopoly_dice())


6
7
5
3
9
9
7
6
5
22


Q10.

In [8]:
def my_n_primes(n):
    if not isinstance(n, int) or n <= 0:
      return []
    primes = []
    num = 2  # Start checking for primes from 2
    while len(primes) < n:
        is_prime = True
        for i in range(2, int(num**0.5) + 1):  # Optimization: check divisibility up to sqrt(num)
            if num % i == 0:
                is_prime = False
                break
        if is_prime:
            primes.append(num)
        num += 1
    return primes
my_n_primes(5)

[2, 3, 5, 7, 11]

Q13.

In [9]:
def my_connectivity_mat_2_dict(C, names):
    if not isinstance(C, list) or not all(isinstance(row, list) for row in C) or not names:
        return {} # Handle invalid input

    n = len(C)
    if n != len(names) or any(len(row) != n for row in C):
        return {} # Handle invalid input

    node = {}
    for i in range(n):
        connected_indices = []
        for j in range(n):
            if C[i][j] == 1:
                connected_indices.append(j)
        node[names[i]] = connected_indices
    return node

C = [[0, 1, 0],
     [0, 0, 1],
     [1, 0, 0]]
names = ["A", "B", "C"]

node_dict = my_connectivity_mat_2_dict(C, names)
print(node_dict)
# Expected output: {'A': [1], 'B': [2], 'C': [0]}

{'A': [1], 'B': [2], 'C': [0]}


# CHAPTER 6

Q2.

In [10]:
def my_chebyshev_poly1(n, x):
    if not isinstance(n, int) or n < 0 or not isinstance(x, list):
        return []
        
    results = []
    for val in x:
        if n == 0:
            results.append(1)
        elif n == 1:
            results.append(val)
        else:
            t_prev = 1  # T_{n-2}
            t_curr = val  # T_{n-1}
            for i in range(2, n + 1):
                t_next = 2 * val * t_curr - t_prev
                t_prev = t_curr
                t_curr = t_next
            results.append(t_curr)
            
    return results

n = 3
x_values = [-1, 0, 1, 0.5]
y_values = my_chebyshev_poly1(n, x_values)
print(f"T_{n}({x_values}) = {y_values}") 
# Expected Output: T_3([-1, 0, 1, 0.5]) = [-1, 0, 1, -0.125]

T_3([-1, 0, 1, 0.5]) = [-1, 0, 1, -1.0]


Q3.

In [11]:
def my_ackermann(m, n):
    if not isinstance(m, int) or not isinstance(n, int) or m < 0 or n < 0:
        return None  # Handle invalid input

    if m == 0:
        return n + 1
    elif m > 0 and n == 0:
        return my_ackermann(m - 1, 1)
    elif m > 0 and n > 0:
        return my_ackermann(m - 1, my_ackermann(m, n - 1))
    else:
        return None
print(my_ackermann(1,5))

7


Q6.

In [12]:
def my_golden_ratio(n):
    if not isinstance(n, int) or n <= 0:
      return None

    if n == 1:
        return 1
    else:
        return 1 + 1 / my_golden_ratio(n - 1)
print(my_golden_ratio(5)) 

1.6


Q8.

In [13]:
def generate_pascal_row(m):
    if not isinstance(m, int) or m < 0:
        return []

    if m == 0:  # Handle the 0th row case
        return [1]

    row = []
    for n in range(m):
        row.append(comb(m - 1, n))  # Use the combinatorics formula
    return row

def generate_pascal_triangle(num_rows):
    if not isinstance(num_rows, int) or num_rows < 0:
        return []

    triangle = []
    for m in range(num_rows):
        triangle.append(generate_pascal_row(m))
    return triangle

from math import comb  # Import the combinatorics function

# Example usage (single row):
row_number = 5
pascal_row = generate_pascal_row(row_number)
print(f"Row {row_number}: {pascal_row}")  
# Output: Row 5: [1, 4, 6, 4, 1]

num_rows = 6
pascal_triangle = generate_pascal_triangle(num_rows)
for row in pascal_triangle:
    print(row)

Row 5: [1, 4, 6, 4, 1]
[1]
[1]
[1, 1]
[1, 2, 1]
[1, 3, 3, 1]
[1, 4, 6, 4, 1]


Q9.

In [23]:
import numpy as np
def my_spiral_ones(n):
    spi = np.zeros((n, n))
    if n == 1:
        spi = np.array([[1]])
    elif n % 4 == 1 and n > 1:
        spi[:1, :] = 1
        spi[1:n, :n-1] = my_spiral_ones(n-1)
    elif n % 4 == 2:
        spi[:, n-1:] = 1
        spi[:n-1, :n-1] = my_spiral_ones(n-1)
    elif n % 4 == 3:
        spi[n-1:, :] = 1
        spi[:n-1, 1:n] = my_spiral_ones(n-1)
    elif n % 4 == 0:
        spi[:, :1] = 1
        spi[1:n, 1:n] = my_spiral_ones(n-1)
    return spi.astype(np.int32)

my_spiral_ones(5)

array([[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 0],
       [1, 0, 1, 1, 0],
       [1, 0, 0, 1, 0],
       [1, 1, 1, 1, 0]], dtype=int32)