# ---------------------- CHAP 1 --------------------

 Q10. Although a year is considered to be 365 days long, a more exact figure is 365.24 days. As a
 consequence, if we held to the standard 365-day year, we would gradually lose that fraction of the
 day over time, and seasons and other astronomical events would not occur as expected. To keep
 the timescale on tract, a leap year is a year that includes an extra day, February 29, to keep the
 timescale on track. Leap years occur on years that are exactly divisible by 4, unless it is exactly
 divisible by 100, unless it is divisible by 400. For example, the year 2004 is a leap year, the year
 1900 is not a leap year, and the year 2000 is a leap year. Compute the number of leap years between
 the years 1500 and 2010.

In [28]:
def is_leap_year(year):
    return (year % 4 == 0 and year % 100 != 0) or (year % 400 == 0)

leap_years = [year for year in range(1500, 2011) if is_leap_year(year)]
print(len(leap_years))


124


Q11. A very powerful approximation for π was developed by Srinivasa Ramanujan. The approximation is:

$$\frac{1}{\pi} \approx \frac{2\sqrt{2}}{9801} \sum_{k=0}^{N} \frac{(4k)!(1103 + 26390k)}{(k!)^4 396^{4k}}$$

Use Ramanujan's formula for N = 0 and N = 1 to approximate π. Compare your approximation with Python's stored value for π. Hint: 0! = 1 by definition.

In [29]:
import math

def ramanujan_pi(N):
    total = 0
    for k in range(N + 1):
        num = math.factorial(4 * k) * (1103 + 26390 * k)
        denom = (math.factorial(k) ** 4) * (396 ** (4 * k))
        total += num / denom
    return (2 * math.sqrt(2) / 9801) * total

pi_approx_0 = 1 / ramanujan_pi(0)
pi_approx_1 = 1 / ramanujan_pi(1)

print(pi_approx_0)
print(pi_approx_1)
print(math.pi)

3.1415927300133055
3.1415926535897936
3.141592653589793


**12. Hyperbolic Sine Calculation**

The hyperbolic sine (sinh) is defined as:

$$sinh(x) = \frac{e^x - e^{-x}}{2}$$

Compute sinh for *x* = 2 using exponentials. Verify that the result is indeed the hyperbolic sin using Python's function `sinh` in the `math` module.

In [30]:
x = 2
sinh_x = (math.exp(x) - math.exp(-x)) / 2
print(sinh_x)

# Verify using Python's math.sinh function
sinh_x_math = math.sinh(x)
print(sinh_x_math)

# Check if both results are the same
print(sinh_x == sinh_x_math)

3.626860407847019
3.626860407847019
True


**13. Trigonometric Identity Verification**

Verify that:

$$sin^2(x) + cos^2(x) = 1$$

for *x* = π, π/2, π/4, π/6.


In [31]:
angles = [math.pi, math.pi/2, math.pi/4, math.pi/6]
"""
This script verifies the trigonometric identity sin^2(x) + cos^2(x) = 1 for a given set of angles.

The angles used for verification are:
- π (pi)
- π/2 (pi divided by 2)
- π/4 (pi divided by 4)
- π/6 (pi divided by 6)

For each angle, the script calculates the value of sin^2(x) + cos^2(x) and stores the results in a list named `identity_verification`.

Finally, the script prints the list `identity_verification` to show the results of the identity verification for each angle.
"""
identity_verification = [(math.sin(x)**2 + math.cos(x)**2) for x in angles]
print(identity_verification)

[1.0, 1.0, 1.0, 1.0]


**14. Sine of 87 Degrees**

Compute sin 87°.


In [32]:
# Convert 87 degrees to radians
angle_degrees = 87
angle_radians = math.radians(angle_degrees)

# Compute the sine of 87 degrees
sine_87 = math.sin(angle_radians)
print(sine_87)

0.9986295347545738


**15. Generating an AttributeError**

Write a Python statement that generates the following error:

`AttributeError: module 'math' has no attribute 'sni'`

Hint: `sni` is a misspelling of the function `sin`.

In [33]:
# This will generate an AttributeError because 'sni' is not a valid attribute of the 'math' module
math.sni(0)

AttributeError: module 'math' has no attribute 'sni'

**16. Generating a TypeError**

Write a Python statement that generates the following error:

`TypeError: sin() takes exactly one argument (0 given)`

Hint: Input arguments refers to the input of a function (any function); for example, the input in sin(π/2) is π/2.

In [1]:
math.sin()

NameError: name 'math' is not defined

**17. Law of Noncontradiction**

If P is a logical expression, the law of noncontradiction states that P AND (NOT P) is always false. Verify this for P true and P false.

In [8]:
# Define logical expressions
P_true = True
P_false = False

# Verify the law of noncontradiction for P_true
# According to the law of noncontradiction, P AND (NOT P) should always be False
noncontradiction_true = P_true and not P_true

# Verify the law of noncontradiction for P_false
# According to the law of noncontradiction, P AND (NOT P) should always be False
noncontradiction_false = P_false and not P_false

# Print the results
print(f"Verification of law of noncontradiction for P = True: {noncontradiction_true}")  # Should print False
print(f"Verification of law of noncontradiction for P = False: {noncontradiction_false}")  # Should print False

Verification of law of noncontradiction for P = True: False
Verification of law of noncontradiction for P = False: False


**18. De Morgan's Rule**

Let P and Q be logical expressions. De Morgan's rule states:

*   NOT (P OR Q) = (NOT P) AND (NOT Q)
*   NOT (P AND Q) = (NOT P) OR (NOT Q)

Generate the truth tables for each statement to show that De Morgan's rule is always true.

In [9]:
def verify_de_morgan():
    # All possible combinations of P and Q
    combinations = [(True, True), (True, False), (False, True), (False, False)]
    
    print("Truth Table for First Rule: NOT (P OR Q) = (NOT P) AND (NOT Q)")
    print("P\tQ\tP OR Q\tNOT(P OR Q)\t(NOT P) AND (NOT Q)\tEqual?")
    print("-" * 65)
    
    for P, Q in combinations:
        left_side = not (P or Q)
        right_side = (not P) and (not Q)
        equal = left_side == right_side
        print(f"{P}\t{Q}\t{P or Q}\t{left_side}\t\t{right_side}\t\t{equal}")
    
    print("\nTruth Table for Second Rule: NOT (P AND Q) = (NOT P) OR (NOT Q)")
    print("P\tQ\tP AND Q\tNOT(P AND Q)\t(NOT P) OR (NOT Q)\tEqual?")
    print("-" * 65)
    
    for P, Q in combinations:
        left_side = not (P and Q)
        right_side = (not P) or (not Q)
        equal = left_side == right_side
        print(f"{P}\t{Q}\t{P and Q}\t{left_side}\t\t{right_side}\t\t{equal}")

verify_de_morgan()

Truth Table for First Rule: NOT (P OR Q) = (NOT P) AND (NOT Q)
P	Q	P OR Q	NOT(P OR Q)	(NOT P) AND (NOT Q)	Equal?
-----------------------------------------------------------------
True	True	True	False		False		True
True	False	True	False		False		True
False	True	True	False		False		True
False	False	False	True		True		True

Truth Table for Second Rule: NOT (P AND Q) = (NOT P) OR (NOT Q)
P	Q	P AND Q	NOT(P AND Q)	(NOT P) OR (NOT Q)	Equal?
-----------------------------------------------------------------
True	True	True	False		False		True
True	False	False	True		True		True
False	True	False	True		True		True
False	False	False	True		True		True


**19. Conditions for a False Expression**

Under what conditions for P and Q is (P AND Q) OR (P AND (NOT Q)) false?


In [10]:
def test_expression():
    # All possible combinations of P and Q
    combinations = [(True, True), (True, False), (False, True), (False, False)]
    
    print("Truth Table for (P AND Q) OR (P AND (NOT Q))")
    print("P\tQ\tP AND Q\tP AND (NOT Q)\tResult")
    print("-" * 50)
    
    for P, Q in combinations:
        term1 = P and Q
        term2 = P and (not Q)
        result = term1 or term2
        print(f"{P}\t{Q}\t{term1}\t{term2}\t\t{result}")
        
test_expression()

Truth Table for (P AND Q) OR (P AND (NOT Q))
P	Q	P AND Q	P AND (NOT Q)	Result
--------------------------------------------------
True	True	True	False		True
True	False	False	True		True
False	True	False	False		False
False	False	False	False		False


**20. Equivalent Expression for OR**

Construct an equivalent logical expression for OR using only AND and NOT.


In [18]:
def test_or_equivalent():
    # De Morgan's Law states that: P OR Q = NOT(NOT P AND NOT Q)
    # Let's test this for all possible combinations
    combinations = [(True, True), (True, False), (False, True), (False, False)]
    
    print("Truth Table for OR vs NOT(NOT P AND NOT Q)")
    print("P\tQ\tP OR Q\tNOT(NOT P AND NOT Q)\tEqual?")
    print("-" * 60)
    
    for P, Q in combinations:
        regular_or = P or Q
        equivalent = not(not P and not Q)
        equal = regular_or == equivalent
        print(f"{P}\t{Q}\t{regular_or}\t{equivalent}\t\t{equal}")

test_or_equivalent()

Truth Table for OR vs NOT(NOT P AND NOT Q)
P	Q	P OR Q	NOT(NOT P AND NOT Q)	Equal?
------------------------------------------------------------
True	True	True	True		True
True	False	True	True		True
False	True	True	True		True
False	False	False	False		True


**21. Equivalent Expression for AND**

Construct an equivalent logical expression for AND using only OR and NOT.

In [19]:
def test_and_equivalent():
    # De Morgan's Law can be used: P AND Q = NOT(NOT P OR NOT Q)
    # Let's test this for all possible combinations
    combinations = [(True, True), (True, False), (False, True), (False, False)]
    
    print("Truth Table for AND vs NOT(NOT P OR NOT Q)")
    print("P\tQ\tP AND Q\tNOT(NOT P OR NOT Q)\tEqual?")
    print("-" * 60)
    
    for P, Q in combinations:
        regular_and = P and Q
        equivalent = not(not P or not Q)
        equal = regular_and == equivalent
        print(f"{P}\t{Q}\t{regular_and}\t{equivalent}\t\t{equal}")

test_and_equivalent()

Truth Table for AND vs NOT(NOT P OR NOT Q)
P	Q	P AND Q	NOT(NOT P OR NOT Q)	Equal?
------------------------------------------------------------
True	True	True	True		True
True	False	False	False		True
False	True	False	False		True
False	False	False	False		True


**22. Equivalent Expression for XOR**

The logical operator XOR has the following truth table (see Fig. 1.18 - *This would need to be included if available*). Construct an equivalent logical expression for XOR using only AND, OR, and NOT that has the same truth table.

In [20]:
def test_xor_equivalent():
    # XOR can be expressed as: (P AND NOT Q) OR (NOT P AND Q)
    combinations = [(True, True), (True, False), (False, True), (False, False)]
    
    print("Truth Table for XOR vs (P AND NOT Q) OR (NOT P AND Q)")
    print("P\tQ\tP XOR Q\tEquivalent\tEqual?")
    print("-" * 50)
    
    for P, Q in combinations:
        regular_xor = P != Q  # Python's != operator behaves like XOR for booleans
        equivalent = (P and not Q) or (not P and Q)
        equal = regular_xor == equivalent
        print(f"{P}\t{Q}\t{regular_xor}\t{equivalent}\t{equal}")

test_xor_equivalent()

Truth Table for XOR vs (P AND NOT Q) OR (NOT P AND Q)
P	Q	P XOR Q	Equivalent	Equal?
--------------------------------------------------
True	True	False	False	True
True	False	True	True	True
False	True	True	True	True
False	False	False	False	True


**23. Python Calculation**

Do the following calculation at the Python command prompt:

e² sin(π/6) + logₑ(3) cos(π/9) – 5³


In [21]:
# Calculate e² sin(π/6) + logₑ(3) cos(π/9) – 5³
result = (math.e ** 2) * math.sin(math.pi/6) + math.log(3) * math.cos(math.pi/9) - 5**3
print(result)

-120.27311408976854


**24. Python Logical and Comparison Operations**

Do the following logical and comparison operations at the Python command prompt. You may assume that P and Q are logical expressions.

*   For P = 1 and Q = 1, compute NOT(P) AND NOT(Q).
*   For a = 10 and b = 25, compute (a < b) AND (a = b).

In [22]:
# For P = 1 and Q = 1, compute NOT(P) AND NOT(Q)
P = 1
Q = 1
result_1 = not P and not Q
print(result_1)

# For a = 10 and b = 25, compute (a < b) AND (a == b)
a = 10
b = 25
result_2 = (a < b) and (a == b)
print(result_2)

False
False


# ------------------ CHAP 2 ----------------------------

**1. Variable Assignment and Clearing**

*   Assign the value 2 to the variable *x* and the value 3 to the variable *y*.
*   Clear just the variable *x*.

In [21]:
x = 2
y = 3
del x  # This clears the variable x while keeping y intact

**2. Generating a NameError**

Write a line of code that generates the following error:

`NameError: name 'x' is not defined`

In [22]:
print(c)

NameError: name 'c' is not defined

**3. Variable Assignments with Calculations**

Let *x* = 10 and *y* = 3. Write a line of code that will make each of the following assignments:

*   *u* = *x* + *y*
*   *v* = *x* * *y*
*   *w* = *x* / *y*
*   *z* = sin(*x*)
*   *r* = 8sin(*x*)
*   *s* = 5sin(*x* * *y*)
*   *p* = *x***y*

In [23]:
x = 10
y = 3

u = x + y
v = x * y
w = x / y
z = math.sin(x)
r = 8 * math.sin(x)
s = 5 * math.sin(x * y)
p = x ** y

print(u, v, w, z, r, s, p)

13 30 3.3333333333333335 -0.5440211108893698 -4.352168887114958 -4.940158120464309 1000


**4. Showing Variables in Jupyter Notebook**

Show all the variables in the Jupyter notebook after you finish Problem 3.


In [24]:
%whos

Variable                Type        Data/Info
---------------------------------------------
angle_degrees           int         87
angle_radians           float       1.5184364492350666
angles                  list        n=4
identity_verification   list        n=4
is_leap_year            function    <function is_leap_year at 0x7f840b76e7a0>
leap_years              list        n=124
math                    module      <module 'math' from '/usr<...>312-x86_64-linux-gnu.so'>
p                       int         1000
pi_approx_0             float       3.1415927300133055
pi_approx_1             float       3.1415926535897936
r                       float       -4.352168887114958
ramanujan_pi            function    <function ramanujan_pi at 0x7f840b76c220>
s                       float       -4.940158120464309
sine_87                 float       0.9986295347545738
sinh_x                  float       3.626860407847019
sinh_x_math             float       3.626860407847019
u                   

**5. String to Float Conversion**

Assign the string "123" to the variable *S*. Convert the string into a float type and assign the output to the variable *N*. Verify that *S* is a string and *N* is a float using the `type` function.

In [25]:
S = "123"
N = float(S)

# Verify types
print(f"S is of type: {type(S)}")
print(f"N is of type: {type(N)}")

S is of type: <class 'str'>
N is of type: <class 'float'>


**6. String Comparison**

Assign the string "HELLO" to the variable *s1* and the string "hello" to the variable *s2*.

*   Use the `==` operator to show that they are not equal.
*   Use the `==` operator to show that *s1* and *s2* are equal if the `lower()` method is used on *s1*.
*   Use the `==` operator to show that *s1* and *s2* are equal if the `upper()` method is used on *s2*.


In [26]:
s1 = "HELLO"
s2 = "hello"

# Compare strings directly
print(f"Direct comparison (s1 == s2): {s1 == s2}")

# Compare with s1 converted to lowercase
print(f"Lowercase comparison (s1.lower() == s2): {s1.lower() == s2}")

# Compare with s2 converted to uppercase
print(f"Uppercase comparison (s1 == s2.upper()): {s1 == s2.upper()}")

Direct comparison (s1 == s2): False
Lowercase comparison (s1.lower() == s2): True
Uppercase comparison (s1 == s2.upper()): True



**7. Using the Print Function**

Use the `print` function to generate the following strings:

*   The world "Engineering" has 11 letters.
*   The word "Book" has 4 letters.

In [27]:
print(f'The word "Engineering" has {len("Engineering")} letters.')
print(f'The word "Book" has {len("Book")} letters.')

The word "Engineering" has 11 letters.
The word "Book" has 4 letters.


**8. Checking for Substring**

Check if "Python" is in "Python is great!".


In [34]:
substring = "Python"
string = "Python is great!"

# Check if substring is in string
is_present = substring in string
print(is_present)

True


**9. Getting the Last Word**

Get the last word "great" from "Python is great!".

In [35]:
string = "Python is great!"
last_word = string.split()[-1]
print(last_word)

great!


In [39]:
**10. List Insertion and Appending**
*   Assign the list `[1, 8, 9, 15]` to a variable `list_a`.
*   Insert `2` at index 1 using the `insert()` method.
*   Append `4` to `list_a` using the `append()` method.

SyntaxError: invalid syntax (3923353011.py, line 1)

In [40]:

list_a = [1, 8, 9, 15]
list_a.insert(1, 2)
list_a.append(4)
print(list_a)

[1, 2, 8, 9, 15, 4]


**11. List Sorting**

Sort `list_a` from problem 10 in ascending order.

In [41]:
list_a.sort()
print(list_a)

[1, 2, 4, 8, 9, 15]


**12. String to List Conversion**

Turn the string "Python is great!" into a list.

In [42]:
string = "Python is great!"
string_list = string.split()
print(string_list)

['Python', 'is', 'great!']


**13. Tuple Creation**

Create a tuple with elements "One" and 1 and assign it to `tuple_a`.

In [43]:
tuple_a = ("One", 1)
print(tuple_a)

('One', 1)


**14. Tuple Element Access**

Get the second element in `tuple_a` from Problem 13.


In [44]:
second_element = tuple_a[1]
print(second_element)

1


**15. Getting Unique Elements**

Get the unique elements from the collection `(2, 3, 2, 3, 1, 2, 5)`.

In [45]:
collection = (2, 3, 2, 3, 1, 2, 5)
unique_elements = set(collection)
print(unique_elements)

{1, 2, 3, 5}


**16. Set Operations**

Assign `(2, 3, 2)` to `set_a` and `(1, 2, 3)` to `set_b`. Obtain the following:

*   Union of `set_a` and `set_b`
*   Intersection of `set_a` and `set_b`
*   Difference of `set_a` to `set_b` using the `difference()` method

In [46]:
set_a = {2, 3, 2}
set_b = {1, 2, 3}

# Union of set_a and set_b
union_set = set_a | set_b
print(f"Union: {union_set}")

# Intersection of set_a and set_b
intersection_set = set_a & set_b
print(f"Intersection: {intersection_set}")

# Difference of set_a to set_b
difference_set = set_a.difference(set_b)
print(f"Difference: {difference_set}")

Union: {1, 2, 3}
Intersection: {2, 3}
Difference: set()


**17. Dictionary Creation and Key Printing**

Create a dictionary that has the keys "A", "B", "C" with values "a", "b", "c" individually. Print all the keys in the dictionary.


In [47]:
my_dict = {"A": "a", "B": "b", "C": "c"}
print(list(my_dict.keys()))

['A', 'B', 'C']


**18. Checking for Key Existence**

Check if key "B" is in the dictionary defined in Problem 17.



In [48]:
is_key_present = "B" in my_dict
print(is_key_present)

True


**19. Array Creation and Calculations**

Create arrays *x* and *y*, where *x* = [1, 4, 3, 2, 9, 4] and *y* = [2, 3, 4, 1, 2, 3]. Compute the assignments from Problem 3 (u = x + y, v = x * y, w = x / y, etc.), assuming element-wise operations.


In [49]:
import numpy as np

# Create arrays x and y
x = np.array([1, 4, 3, 2, 9, 4])
y = np.array([2, 3, 4, 1, 2, 3])

# Perform element-wise operations
u = x + y
v = x * y
w = x / y
z = np.sin(x)
r = 8 * np.sin(x)
s = 5 * np.sin(x * y)
p = x ** y

print("u =", u)
print("v =", v)
print("w =", w)
print("z =", z)
print("r =", r)
print("s =", s)
print("p =", p)

u = [ 3  7  7  3 11  7]
v = [ 2 12 12  2 18 12]
w = [0.5        1.33333333 0.75       2.         4.5        1.33333333]
z = [ 0.84147098 -0.7568025   0.14112001  0.90929743  0.41211849 -0.7568025 ]
r = [ 6.73176788 -6.05441996  1.12896006  7.27437941  3.29694788 -6.05441996]
s = [ 4.54648713 -2.68286459 -2.68286459  4.54648713 -3.75493623 -2.68286459]
p = [ 1 64 81  2 81 64]


**20. Evenly Spaced Array**

Generate an array with size 100 evenly spaced between -10 to 10 using the `linspace` function in NumPy.


In [50]:
evenly_spaced = np.linspace(-10, 10, 100)
print(evenly_spaced)

[-10.          -9.7979798   -9.5959596   -9.39393939  -9.19191919
  -8.98989899  -8.78787879  -8.58585859  -8.38383838  -8.18181818
  -7.97979798  -7.77777778  -7.57575758  -7.37373737  -7.17171717
  -6.96969697  -6.76767677  -6.56565657  -6.36363636  -6.16161616
  -5.95959596  -5.75757576  -5.55555556  -5.35353535  -5.15151515
  -4.94949495  -4.74747475  -4.54545455  -4.34343434  -4.14141414
  -3.93939394  -3.73737374  -3.53535354  -3.33333333  -3.13131313
  -2.92929293  -2.72727273  -2.52525253  -2.32323232  -2.12121212
  -1.91919192  -1.71717172  -1.51515152  -1.31313131  -1.11111111
  -0.90909091  -0.70707071  -0.50505051  -0.3030303   -0.1010101
   0.1010101    0.3030303    0.50505051   0.70707071   0.90909091
   1.11111111   1.31313131   1.51515152   1.71717172   1.91919192
   2.12121212   2.32323232   2.52525253   2.72727273   2.92929293
   3.13131313   3.33333333   3.53535354   3.73737374   3.93939394
   4.14141414   4.34343434   4.54545455   4.74747475   4.94949495
   5.151515

**21. Filtering Array Elements**

Let `array_a` be an array [-1, 0, 1, 2, 0, 3]. Write a command that will return an array consisting of all the elements of `array_a` that are larger than zero. Hint: Use a logical expression as the index of the array.


In [51]:
array_a = np.array([-1, 0, 1, 2, 0, 3])
filtered_array = array_a[array_a > 0]
print(filtered_array)

[1 2 3]


**22. Matrix Transpose**

Create an array (matrix) *y* :
$$
y = \begin{pmatrix}
3 & 5 & 3 \\
2 & 2 & 5 \\
3 & 8 & 9
\end{pmatrix}
$$

and calculate its transpose.

In [52]:
# Create the matrix
y = np.array([[3, 5, 3],
              [2, 2, 5],
              [3, 8, 9]])

# Calculate transpose
y_transpose = y.transpose()
# or alternatively: y_transpose = y.T

print("Original matrix:")
print(y)
print("\nTransposed matrix:")
print(y_transpose)

Original matrix:
[[3 5 3]
 [2 2 5]
 [3 8 9]]

Transposed matrix:
[[3 2 3]
 [5 2 8]
 [3 5 9]]


**23. Zero Array Creation**

Create a 2 x 4 zero array.



In [53]:
zero_array = np.zeros((2, 4))
print(zero_array)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]


**24. Column Modification**

Change the second column in the array created in Problem 23 to 1.


In [54]:
zero_array[:, 1] = 1
print(zero_array)

[[0. 1. 0. 0.]
 [0. 1. 0. 0.]]


**25. Clearing Jupyter Notebook Variables**

Write a magic command to clear all the variables in the Jupyter notebook.

In [55]:
%reset -f

# --------- CHAP 3 ------------

In [56]:
import numpy as np
import math

# 1. Hyperbolic Sine Function
def my_sinh(x):
    """Computes the hyperbolic sine of x.

    Args:
        x: A float.

    Returns:
        The hyperbolic sine of x.
    """
    y = (math.exp(x) - math.exp(-x)) / 2
    return y

# Test cases for my_sinh
print("Test cases for my_sinh:")
print(f"my_sinh(0) = {my_sinh(0)}")
print(f"my_sinh(1) = {my_sinh(1)}")
print(f"my_sinh(2) = {my_sinh(2)}")
print()


Test cases for my_sinh:
my_sinh(0) = 0.0
my_sinh(1) = 1.1752011936438014
my_sinh(2) = 3.626860407847019



In [57]:
# 2. Checkerboard Array Function
def my_checker_board(n):
    """Creates an n x n checkerboard array.

    Args:
        n: A positive integer representing the size of the array.

    Returns:
        A NumPy array representing the checkerboard, or the integer 1 if n=1.
    """
    if n == 1:
        return 1
    else:
        m = np.zeros((n, n), dtype=int)  # Initialize with zeros
        for i in range(n):
            for j in range(n):
                if (i + j) % 2 == 0:
                    m[i, j] = 1
        return m

# Test cases for my_checker_board
print("Test cases for my_checker_board:")
print(f"my_checker_board(1) = {my_checker_board(1)}")
print(f"my_checker_board(2) = \n{my_checker_board(2)}")
print(f"my_checker_board(5) = \n{my_checker_board(5)}")


Test cases for my_checker_board:
my_checker_board(1) = 1
my_checker_board(2) = 
[[1 0]
 [0 1]]
my_checker_board(5) = 
[[1 0 1 0 1]
 [0 1 0 1 0]
 [1 0 1 0 1]
 [0 1 0 1 0]
 [1 0 1 0 1]]


In [58]:
# 3. Triangle Area Function
def my_triangle(b, h):
    """Calculates the area of a triangle.

    Args:
        b: The base of the triangle (float).
        h: The height of the triangle (float).

    Returns:
        The area of the triangle (float).
    """
    area = 0.5 * b * h
    return area

# Test cases for my_triangle
print("Test cases for my_triangle:")
print(f"my_triangle(1, 1) = {my_triangle(1, 1)}")
print(f"my_triangle(2, 1) = {my_triangle(2, 1)}")
print(f"my_triangle(12, 5) = {my_triangle(12, 5)}")
print()

Test cases for my_triangle:
my_triangle(1, 1) = 0.5
my_triangle(2, 1) = 1.0
my_triangle(12, 5) = 30.0



In [59]:
# 4. Matrix Splitting Function
def my_split_matrix(m):
    """Splits a matrix into two halves.

    Args:
        m: A NumPy array (matrix) with at least two columns.

    Returns:
        A list [m1, m2] where m1 is the left half and m2 is the right half.
        The middle column goes to m1 if there's an odd number of columns.
        Returns None if the input is invalid.
    """
    if not isinstance(m, np.ndarray) or m.ndim != 2 or m.shape[1] < 2:
      print("Invalid input: Input must be a 2D numpy array with at least 2 columns")
      return None

    num_cols = m.shape[1]
    midpoint = (num_cols + 1) // 2  # Integer division to handle odd columns

    m1 = m[:, :midpoint]
    m2 = m[:, midpoint:]
    return [m1, m2]

# Test cases for my_split_matrix
print("Test cases for my_split_matrix:")
m = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
m1, m2 = my_split_matrix(m)
print("Input m:")
print(m)
print("Output m1:")
print(m1)
print("Output m2:")
print(m2)
print()

m = np.ones((5, 5))
m1, m2 = my_split_matrix(m)
print("Input m:")
print(m)
print("Output m1:")
print(m1)
print("Output m2:")
print(m2)
print()

#Test case for invalid input
m = np.array([1,2,3])
my_split_matrix(m)

m = [[1,2],[3,4]]
my_split_matrix(m)

Test cases for my_split_matrix:
Input m:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Output m1:
[[1 2]
 [4 5]
 [7 8]]
Output m2:
[[3]
 [6]
 [9]]

Input m:
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
Output m1:
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
Output m2:
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]

Invalid input: Input must be a 2D numpy array with at least 2 columns
Invalid input: Input must be a 2D numpy array with at least 2 columns


In [60]:
import numpy as np
import math

def my_cylinder(r, h):
    """
    Calculate surface area and volume of a cylinder
    Args:
        r (float): radius of the cylinder
        h (float): height of the cylinder
    Returns:
        list: [surface_area, volume]
    """
    # Calculate surface area: 2πr² + 2πrh
    surface_area = 2 * math.pi * r**2 + 2 * math.pi * r * h
    
    # Calculate volume: πr²h
    volume = math.pi * r**2 * h
    
    return [surface_area, volume]

In [61]:
def my_n_odds(a):
    """
    Count odd numbers in an array
    Args:
        a (array): one-dimensional array of floats
    Returns:
        int: count of odd numbers
    """
    # Convert to numpy array if not already
    arr = np.array(a)
    
    # Count numbers where modulo 2 equals 1
    return np.sum(arr.astype(int) % 2 == 1)


In [62]:
def my_twos(m, n):
    """
    Create an m × n array filled with twos
    Args:
        m (int): number of rows
        n (int): number of columns
    Returns:
        numpy.ndarray: m × n array of twos
    """
    # Use numpy's full function to create array of twos
    return np.full((m, n), 2)

# -------------------     Test cases -------------------------------------
print("Testing my_cylinder:")
print(my_cylinder(1, 5))  # Expected: [37.6991, 15.7080]
print(my_cylinder(2, 4))  # Expected: [62.8319, 37.6991]

print("\nTesting my_n_odds:")
print(my_n_odds(np.arange(100)))  # Expected: 50
print(my_n_odds(np.arange(2, 100, 2)))  # Expected: 0

print("\nTesting my_twos:")
print(my_twos(3, 2))  # Expected: [[2, 2], [2, 2], [2, 2]]
print(my_twos(1, 4))  # Expected: [[2, 2, 2, 2]]

Testing my_cylinder:
[37.69911184307752, 15.707963267948966]
[75.39822368615503, 50.26548245743669]

Testing my_n_odds:
50
0

Testing my_twos:
[[2 2]
 [2 2]
 [2 2]]
[[2 2 2 2]]


In [63]:
# 8. Lambda function for subtraction
subtract = lambda x, y: x - y


In [64]:
# 9. String concatenation function
def add_string(s1, s2):
    """
    Concatenates two strings
    Args:
        s1 (str): first string
        s2 (str): second string
    Returns:
        str: concatenated string
    """
    return s1 + s2

In [65]:
fun()

def bad_function():
no_indent = "This will raise IndentationError"

IndentationError: expected an indented block after function definition on line 3 (616331257.py, line 4)

In [66]:
# 11. Greeting function
def greeting(name, age):
    """
    Creates a personalized greeting
    Args:
        name (str): person's name
        age (float): person's age
    Returns:
        str: formatted greeting message
    """
    return f"Hi, my name is {name} and I am {int(age)} years old."


In [67]:
# 12. Donut area function
def my_donut_area(r1, r2):
    """
    Calculates the area of a donut shape between two circles
    Args:
        r1 (array): radius of inner circles
        r2 (array): radius of outer circles (r2 > r1)
    Returns:
        array: areas of donut shapes
    """
    # Convert inputs to numpy arrays
    r1 = np.array(r1)
    r2 = np.array(r2)
    
    # Calculate areas using π(R² - r²)
    return np.pi * (r2**2 - r1**2)


In [68]:
# 13. Within tolerance function
def my_within_tolerance(A, a, tol):
    """
    Finds indices where absolute difference is within tolerance
    Args:
        A (array): input array
        a (float): reference value
        tol (float): tolerance value
    Returns:
        array: indices where |A - a| < tol
    """
    A = np.array(A)
    return np.where(np.abs(A - a) < tol)[0]


### ---------- TESTING -----------

In [70]:
# Test cases and examples
if __name__ == "__main__":
    # Test subtract lambda
    print("Testing subtract lambda:")
    print(subtract(5, 3))  # Expected: 2
    print(subtract(10, 7))  # Expected: 3
    
    # Test add_string
    print("\nTesting add_string:")
    s1 = add_string("Programming", " ")
    s2 = add_string("is ", "fun!")
    print(add_string(s1, s2))  # Expected: "Programming is fun!"
    
    # Test greeting
    print("\nTesting greeting:")
    print(greeting("John", 26))  # Expected: "Hi, my name is John and I am 26 years old."
    print(greeting("Kate", 19))  # Expected: "Hi, my name is Kate and I am 19 years old."
    
    # Test my_donut_area
    print("\nTesting my_donut_area:")
    r1_test = np.array([1, 2, 3])
    r2_test = np.array([2, 4, 5])
    print(my_donut_area(r1_test, r2_test))
    
    # Test my_within_tolerance
    print("\nTesting my_within_tolerance:")
    A_test = np.array([1.0, 1.1, 2.0, 1.2, 0.9])
    print(my_within_tolerance(A_test, 1.0, 0.15))  # Expected: indices where values are within 0.15 of 1.0

Testing subtract lambda:
2
3

Testing add_string:
Programming is fun!

Testing greeting:
Hi, my name is John and I am 26 years old.
Hi, my name is Kate and I am 19 years old.

Testing my_donut_area:
[ 9.42477796 37.69911184 50.26548246]

Testing my_within_tolerance:
[0 1 4]


In [71]:
import numpy as np

def bounding_array(A, top, bottom):
    """
    Bound array A between bottom and top values
    Args:
        A (array): input array
        top (float): upper bound
        bottom (float): lower bound (must be less than top)
    Returns:
        array: bounded array where values are clipped to [bottom, top] range
    """
    # Convert input to numpy array if it isn't already
    A = np.array(A)
    
    # Use numpy's clip function to bound the array
    return np.clip(A, bottom, top)

# Test cases with examples
if __name__ == "__main__":
    print("Example 1: Basic bounding")
    test_array = np.array([0.5, 1.5, 2.5, 3.5, 4.5])
    result = bounding_array(test_array, 3.0, 1.0)
    print(f"Input array: {test_array}")
    print(f"Bounded (1.0 to 3.0): {result}")
    # Expected: [1.0, 1.5, 2.5, 3.0, 3.0]
    
    print("\nExample 2: Array with values within bounds")
    test_array2 = np.array([1.2, 1.5, 1.8, 2.0, 2.2])
    result2 = bounding_array(test_array2, 2.5, 1.0)
    print(f"Input array: {test_array2}")
    print(f"Bounded (1.0 to 2.5): {result2}")
    # Expected: original values (all within bounds)
    
    print("\nExample 3: Extreme values")
    test_array3 = np.array([-5.0, 0.0, 5.0, 10.0, 15.0])
    result3 = bounding_array(test_array3, 7.0, -2.0)
    print(f"Input array: {test_array3}")
    print(f"Bounded (-2.0 to 7.0): {result3}")
    # Expected: [-2.0, 0.0, 5.0, 7.0, 7.0]

Example 1: Basic bounding
Input array: [0.5 1.5 2.5 3.5 4.5]
Bounded (1.0 to 3.0): [1.  1.5 2.5 3.  3. ]

Example 2: Array with values within bounds
Input array: [1.2 1.5 1.8 2.  2.2]
Bounded (1.0 to 2.5): [1.2 1.5 1.8 2.  2.2]

Example 3: Extreme values
Input array: [-5.  0.  5. 10. 15.]
Bounded (-2.0 to 7.0): [-2.  0.  5.  7.  7.]
